# This is a basic workflow to help you get started with Actions
# stolen from newb engine lmaooo

name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master, main ]
  #pull_request:
  #  branches: [ master, main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildLinux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.1.5
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install lime 7.8.0
          haxelib install openfl 9.0.2
          haxelib --never install flixel 4.8.1
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-addons
          haxelib install newgrounds
          haxelib git polymod https://github.com/larsiusprime/polymod.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib install hxcpp-debug-server
          haxelib install linc_luajit
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git
          haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
          haxelib git faxe https://github.com/uhrobots/faxe
          haxelib git polymod https://github.com/larsiusprime/polymod.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib install actuate
          apt g++-multilib
          apt gcc-multilib
          haxelib git extension-webm https://github.com/KadeDev/extension-webm
          lime rebuild extension-webm linux
          haxelib list
      - name: Create APIStuff
        uses: "finnp/create-file-action@master"
        env:
          FILE_NAME: "source/APIStuff.hx"
          FILE_DATA: "package;class APIStuff{public static var API:String = '';public static var EncKey:String = '';}"
      - name: Compile
        run: haxelib run lime build html5
      - name: Archive
        run: tar -czf bin.tar.gz 'export/release/html5/bin' 
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with:
          name: linuxBuild
          path: bin.tar.gz
